language: cpp
before_install: sudo apt-get update
install: sudo apt-get install build-essential libssl-dev libboost-all-dev libcurl4-openssl-dev libdb5.3-dev libdb5.3++-dev git qt-sdk libminiupnpc-dev qt4-default
script: cd src && make -f makefile.unix USE_UPNP=0 && cd .. && qmake "USE_UPNP=0" && make
